apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apmServer.name }}-metricbeat-config
data:
  metricbeat.yml: |
    metricbeat:
      modules:
      - module: beat
        xpack.enabled: true
        hosts: ["http://localhost:5066"]
        period: 10s
        metricsets:
          - stats
          - state
    output:
      elasticsearch:
        hosts:
          - https://{{ .Values.elasticsearch.name }}-es-http.{{ .Release.Namespace }}.svc:9200
        password: '${ELASTIC_MONITORING_PASS}'
        username: {{ .Release.Namespace }}-{{ .Values.elasticsearch.name }}-{{ .Release.Namespace }}-{{ .Values.elasticsearch.name }}-beat-es-mon-user
        ssl:
          certificate_authorities:
            - /usr/share/metricbeat/certs/ca.crt
          verification_mode: certificate
    processors:
    - add_cloud_metadata: null
    - add_host_metadata: null
