---
{{- if .Values.kibana.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.kibana.name }}-ingress
  # TODO kdybychom nechteli vypinat https
  # to se pak bude hodit na ten elasticsearch hlavne asi
  # annotations:
  # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  # annotations:
  #   traefik.ingress.kubernetes.io/service.scheme: https
spec:
  # todo zmenit pak u nas na nginx
  ingressClassName: traefik
  rules:
    {{- range .Values.kibana.hosts }}
    - host: {{ . | quote }}
      http:
          paths:
            - path: "/"
              pathType: ImplementationSpecific
              backend:
                service:
                  name: {{ $.Values.kibana.name }}-kb-http
                  port:
                    number: 5601
    {{- end }}
  tls:
    - hosts:
        - kibana-main.rancher.local
{{- end }}