---
{{- if .Values.elasticsearch.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
    version: {{ .Values.clusterVersion }}
    transport:
      tls:
        certificate:
          # workaround pro to abychom nemuseli rucne kopirovat certifikaty pro cross cluster search
          # jinak oficialni reseni je az ve vyssi licenci
          # pro nase ucely ale je tohle dostacujici, cross cluster repilikaci stejne nepotrebujeme
          secretName: {{ .Values.mainClusterName }}-es-transport-ca-internal
    nodeSets:
      - name: default
        count: 1
        config:
          node.store.allow_mmap: false
        podTemplate:
          metadata:
            annotations:
                co.elastic.metrics/raw: |
                  [
                    {
                      "module": "elasticsearch",
                      "enabled": true,
                      "metricsets": ["cluster_stats","enrich","index","index_recovery","index_summary","ml_job","node_stats","shard"],
                      "period": "10s",
                      "hosts": "https://${data.host}:${data.ports.https}",
                      "username": "elastic",
                      "password": "${kubernetes.elk.{{ .Values.elasticsearch.name }}-es-elastic-user.elastic}",
                      "ssl.verification_mode": "none",
                      "xpack.enabled": "true"
                    }
                  ]
          spec:
            # TODO prijde mne ze tohle neni potreba, mozna to meli pro debug ?
            # securityContext:
            #   runAsUser: 1000
            containers:
              - name: elasticsearch
                env:
                  - name: INTERNAL_USR_PASS
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.elasticsearch.name }}-es-internal-users
                        key: elastic-internal
                  - name: ELASTIC_USR_PASS
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.elasticsearch.name }}-es-elastic-user
                        key: elastic
                  - name: INTERNAL_PROBE_PASS
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.elasticsearch.name }}-es-internal-users
                        key: elastic-internal-probe
                  - name: KIBANA_SERVICE_ACCOUNT_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.kibana.name }}-kibana-user
                        key: token
                  - name: ELASTIC_MONITORING_PASS
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.elasticsearch.name }}-es-internal-users
                        key: elastic-internal-monitoring
                  # TODO JE TOHLE POTREBA, NEMAJ TO JEN PRO DEBUG ?
                  # - name: ES_JAVA_OPTS
                  #   value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888
                volumeMounts:
                  - name: elasticsearch-modules
                    mountPath: /usr/share/elasticsearch/modules
                  - name: elasticsearch-lib
                    mountPath: /usr/share/elasticsearch/lib
                  - name: config-ror
                    mountPath: /usr/share/elasticsearch/config/readonlyrest.yml
                    subPath: readonlyrest.yml
                resources:
                  {{- toYaml .Values.elasticsearch.resources | nindent 14 }}
            initContainers:
              # TODO tohle nevim k cemu je, ale maj to vsude :D
              - name: sysctl
                securityContext:
                  runAsUser: 0
                  privileged: true
                command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
              - name: install-ror-es-plugin
                securityContext:
                  allowPrivilegeEscalation: false
                  runAsUser:
                    0
                    # TODO tady by to chtelo idealne ten soubor hostovat nekde u nas
                command:
                  - "/bin/bash"
                  - "-c"
                  - |
                    set -e

                    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch "https://api.beshu.tech/download/es?edition=es&esVersion=$ES_VERSION&email=eck-example%40readonlyrest.com"
                    /usr/share/elasticsearch/jdk/bin/java -jar /usr/share/elasticsearch/plugins/readonlyrest/ror-tools.jar patch

                    cp -r /usr/share/elasticsearch/modules /target/usr/share/elasticsearch
                    cp -r /usr/share/elasticsearch/lib /target/usr/share/elasticsearch
                env:
                  - name: ES_VERSION
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.labels['elasticsearch.k8s.elastic.co/version']
                volumeMounts:
                  - name: elasticsearch-modules
                    mountPath: /target/usr/share/elasticsearch/modules
                  - name: elasticsearch-lib
                    mountPath: /target/usr/share/elasticsearch/lib
            volumes:
              - name: elasticsearch-modules
                emptyDir: {}
              - name: elasticsearch-lib
                emptyDir: {}
              - name: config-ror
                configMap:
                  name: config-readonlyrest.yml
{{- end }}