---
{{- if .Values.kibana.enabled }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.kibana.name }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  version: {{ .Values.clusterVersion }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
  config:
    readonlyrest_kbn.store_sessions_in_index: true
    readonlyrest_kbn.cookiePass: "12345678901234567890123456789012345678901234567890"
    readonlyrest_kbn.logLevel: "info"
    monitoring.kibana.collection.enabled: false
    logging:
      appenders:
        json-layout:
          type: console
          layout:
            type: json
      root:
        appenders: [json-layout]
  podTemplate:
    metadata:
      annotations:
        co.elastic.metrics/raw: |
          [
            {
              "module": "kibana",
              "enabled": true,
              "period": "10s",
              "hosts": "http://${data.host}:${data.ports.http}",
              "username": "elastic",
              "password": "${kubernetes.elk.{{ .Values.elasticsearch.name }}-es-elastic-user.elastic}",
              "ssl.verification_mode": "none",
              "xpack.enabled": "true"
            }
          ]
    spec:
      containers:
        - name: kibana
          volumeMounts:
            - name: kibana-plugins
              mountPath: /usr/share/kibana/plugins
            - name: kibana-node-modules-kbn
              mountPath: /usr/share/kibana/node_modules/@kbn
            - name: kibana-src
              mountPath: /usr/share/kibana/src
            - name: kibana-xpack-plugins
              mountPath: /usr/share/kibana/x-pack/plugins
      initContainers:
        - name: install-ror-kbn-plugin
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          # TODO tady by to chtelo idealne ten soubor hostovat nekde u nas
          command:
            - "/bin/bash"
            - "-c"
            - |
              set -e

              /usr/share/kibana/bin/kibana-plugin install "https://api.beshu.tech/download/kbn?esVersion=$KBN_VERSION&edition=kbn_universal&email=eck-example%40readonlyrest.com"
              /usr/share/kibana/node/bin/node /usr/share/kibana/plugins/readonlyrestkbn/ror-tools.js patch

              cp -r /usr/share/kibana/node_modules/@kbn /target/usr/share/kibana/node_modules
              cp -r /usr/share/kibana/src /target/usr/share/kibana
              cp -r /usr/share/kibana/x-pack/plugins /target/usr/share/kibana/x-pack
          env:
            - name: KBN_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['kibana.k8s.elastic.co/version']
          volumeMounts:
            - name: kibana-plugins
              mountPath: /usr/share/kibana/plugins
            - name: kibana-node-modules-kbn
              mountPath: /target/usr/share/kibana/node_modules/@kbn
            - name: kibana-src
              mountPath: /target/usr/share/kibana/src
            - name: kibana-xpack-plugins
              mountPath: /target/usr/share/kibana/x-pack/plugins
      volumes:
        - name: kibana-plugins
          emptyDir: {}
        - name: kibana-node-modules-kbn
          emptyDir: {}
        - name: kibana-src
          emptyDir: {}
        - name: kibana-xpack-plugins
          emptyDir: {}
  # TODO bez tohodle mne nefunguje trafik routovani. takhle ta kibana je na http
  http:
    tls:
      selfSignedCertificate:
        disabled: true
{{- end }}