---
{{- if .Values.apmServer.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apmServer.nginx.name }}
  labels:
    {{- include "apmServer.nginx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apmServer.nginx.selectorLabels" . | nindent 4 }}
{{- end }}