apiVersion: v1
kind: Secret
metadata:
  name: es-main-users
type: kubernetes.io/basic-auth
stringData:
  username: test
  password: testtest
  roles: superuser # optional, not part of kubernetes.io/basic-auth
# todo lepsi bude vygenerovat skrze ty hashe eventualne
# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html
