---
{{- if .Values.metricbeat.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.metricbeat.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.metricbeat.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metricbeat.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}