---
{{- if .Values.metricbeat.enabled }}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Values.metricbeat.name }}
  labels:
    {{- include "metricbeat.labels" . | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  type: metricbeat
  version: {{ .Values.clusterVersion }}
  elasticsearchRef:
    name: {{ .Values.mainClusterName }}
  config:
    logging:
      json: true
      level: debug
    metricbeat:
      autodiscover:
        providers:
          - type: kubernetes
            scope: cluster
            hints:
              enabled: "true"
            node: ${NODE_NAME}
            type: kubernetes
  deployment:
    podTemplate:
      metadata:
        annotations:
          co.elastic.logs/json.keys_under_root: "true"
          co.elastic.logs/json.add_error_key: "true"
          co.elastic.logs/json.message_key: "message"
      spec:
        serviceAccountName: {{ .Values.metricbeat.name }}
        automountServiceAccountToken: true
        # required to read /etc/beat.yml
        securityContext:
          runAsUser: 0
        containers:
          - name: metricbeat
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
{{- end }}