---
{{- if .Values.metricbeat.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.metricbeat.name }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - namespaces
      - pods
      - nodes
      - secrets
      - events
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["apps"]
    resources:
     - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
{{- end }}