---
kafka_hosts:
  - kafka.elk.svc.cluster.local:9092
kafka_group_id: test
logstash_pipelines:
  - datastream_name: "test.stream"
    topics_pattern: "stream.*"
  - index_name: "test-index"
    topics_pattern: "index.*"
